#demo.yaml
#python versions

name: Stock Prediction app
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r senti/requirements.txt
    - name: train_model
      run: |
        python3 stockapi/app.py
    
    - name: test with pytest
      run: |
        pytest stockapi/tests/api_test.py
